services:
  web:
    image: nginx:latest
    container_name: compose-nginx

    environment:
     APP_ENV: development

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3   
 
    ports:
      - "8082:80"

    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  client:
    image: curlimages/curl:latest
    depends_on:
        web:
          condition: service_healthy
